import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Slider from '../components/slider'
import Tourculture from '../components/tourculture'
import PopularTrips from '../components/populartrips'
import Destination from '../components/destination'
import Form from '../components/form'
import { useState } from 'react'
import Populartours from '../components/populartours'
import { BiSupport } from 'react-icons/bi'
import { AiFillCloseCircle, AiOutlineForm } from 'react-icons/ai'
import Header from '../components/header'
import Footer from '../components/footer'

export default function Home() {
  const [showForm, setshowForm] = useState(false);
  return (
    <div>
      <Head>
        <title>Viva India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className='max-lg:bg-white lg:bg-transparent lg:absolute top-0 z-50'>
          <Header />
        </div>
        <div className='grid grid-cols-1 h-[40rem]'>
          <div className=' relative z-20 h-[40rem]'>
            <Slider />
          </div>
          {(showForm) ?
            <div className=' max-md:hidden flex fixed z-50 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2'><Form /><button className='flex' onClick={() => setshowForm(!showForm)}><AiFillCloseCircle className=' text-2xl' /></button></div> : <></>}
        </div>

        <div ><button className='flex bg-redmix text-white font-Roboto p-4 w-fit z-50 items-center text-xl gap-1 h-11 fixed bottom-11 right-6' onClick={() => setshowForm(!showForm)}><div className='text-white'><AiOutlineForm /></div> <div>Contact Us</div></button></div>

        <Populartours />

        <div className='flex lg:hidden gap-3 items-center h-4/5 justify-center from-red-100 via-red-300 to-blue-500 bg-gradient-to-br'>
        </div>

        <div>
          <Tourculture />
        </div>
        <div className='hidden'>
          <Container />
        </div>
        <div>
          <PopularTrips />
        </div>

        <div>
          <Destination />
        </div>
      </main>

      <Footer />
    </div>
  )
}
